### ISSUE TITLE
Build fails with `sh: 1: cargo: not found`

### ISSUE THREAD

**Issue by kariae** [rust-embedded/cross#260]
The build fails on a Docker container with `sh: 1: cargo: not found`, the Docker container is run with a custom image that contains Docker with a wrapper to have DinD working, and Rust nightly `docker run -it -v `pwd`:/var/tmp -v /var/run/docker.sock:/var/run/docker.sock kariae/docker-rust-nightly sh` the command fails with `sh: 1: cargo: not found`

**Comment by evanjs** [comment]
I am also encountering this issue.
Nothing special about my setup, though.
```
[evanjs@nixentoo:~/src/scratch/sdl2test]$ cross build --target x86_64-pc-windows-gnu
Unable to find image 'japaric/x86_64-pc-windows-gnu:v0.1.14' locally
v0.1.14: Pulling from japaric/x86_64-pc-windows-gnu
b8a43e1b7983: Pull complete 
5c5185a06822: Pull complete 
8458c4a4e317: Pull complete 
6d0388b275d4: Pull complete 
56603a33e04b: Pull complete 
2cedd67f6904: Pull complete 
5d40de413ec5: Pull complete 
fbd3dda3b3f5: Pull complete 
ee23f3a81425: Pull complete 
22d70475d56a: Pull complete 
cc2c4c043bf3: Pull complete 
ace8770c3426: Pull complete 
Digest: sha256:b164f497e18f89133de814898d838603b07a6b1feb80b06271ddb3fb86128cc8
Status: Downloaded newer image for japaric/x86_64-pc-windows-gnu:v0.1.14
sh: 1: cargo: not found
```

Using NixOS 19.03 on 4.19.24
Docker: 18.09.2
Cross: 0.1.14
cargo 1.34.0-nightly (5c6aa46e6 2019-02-22)

**Comment by kariae** [comment]
I checked the image and I didn't find the installation of `cargo` which is a little bit tricky, since we use it to build the binaries ?!

**Comment by afiore** [comment]
I am encountering the same problem. I have just tried running `cross build --target aarch64-unknown-linux-musl` and got the following output

```
Unable to find image 'japaric/x86_64-unknown-linux-musl:v0.1.14' locally
v0.1.14: Pulling from japaric/x86_64-unknown-linux-musl
8d51e945c435: Pull complete
d8d21cdaac84: Pull complete
99b5ff394311: Pull complete
3ab3190bc52d: Pull complete
8f2bd7981235: Pull complete
ba0de5bbf3ef: Pull complete
b8380c29d163: Pull complete
e75a875c5cd4: Pull complete
e10da4c5e540: Pull complete
26440e989b5e: Pull complete
b87e83e92416: Pull complete
2e920f245507: Pull complete
Digest: sha256:524b2d33f250ce4e243397b26aab5be7e90d5413b047cc1b9461a62b42b603e6
Status: Downloaded newer image for japaric/x86_64-unknown-linux-musl:v0.1.14
sh: 1: cargo: not found
```

**Comment by wucke13** [comment]
I'm also hit by
```
sh: 1: cargo: not found
failed to resize tty, using default size
sh: 1: cargo: not found
```
On Linux, NixOS 19.03

**Comment by binarylogic** [comment]
Same problem here. It appears to be limited to executing `cross` within a docker image. I'm curious if anyone has workarounds?

**Comment by AluisioASG** [comment]
The problem is that the image uses the host's own Rust install, which in some cases (e.g. NixOS) cannot be run on Ubuntu. You can work around it by building an image with its own Rust install, for example:
```dockerfile
FROM japaric/x86_64-unknown-freebsd:v0.1.4
RUN apt-get update && apt-get install -y wget
RUN mkdir -m777 /opt/rust /opt/cargo
ENV RUSTUP_HOME=/opt/rust CARGO_HOME=/opt/cargo PATH=/opt/cargo/bin:$PATH
RUN wget --https-only --secure-protocol=TLSv1_2 -O- https://sh.rustup.rs | sh /dev/stdin -y
RUN rustup target add x86_64-unknown-freebsd
RUN printf '#!/bin/sh\nexport CARGO_HOME=/opt/cargo\nexec /bin/sh "$@"\n' >/usr/local/bin/sh
RUN chmod +x /usr/local/bin/sh
```
(Rust is installed outside `~` so the user the build runs as can access it. About the last two lines, I wasn't able to override `CARGO_HOME` from the shell profile so I override the shell instead.)

**Comment by wucke13** [comment]
Using something from the host breakes many of the otherwise strong guarantees alike "runs fine with me, will run fine with you" docker has to offer. IMO this should be at least considered to be changed.

**Comment by reitermarkus** [comment]
Have you tried installing `cross` from `master`?

**Comment by ndusart** [comment]
I had still to make some workaround for using `cross` in gitlab-ci even when using the master branch.
But I managed to do it, you can find information in this comment: https://github.com/rust-embedded/cross/issues/273#issuecomment-528300479

**Comment by zonyitoo** [comment]
Same issue was found on circle-ci build: https://circleci.com/gh/shadowsocks/shadowsocks-rust/5

Could that be fixed by your script, too? @AluisioASG

**Comment by tomscript** [comment]
```
# cargo install --git https://github.com/rust-embedded/cross.git
    Updating git repository `https://github.com/rust-embedded/cross.git`
  Installing cross v0.2.0-alpha.1 (https://github.com/rust-embedded/cross.git#2f284acd)
<removed>
    Replaced package `cross v0.1.16` with `cross v0.2.0-alpha.1 (https://github.com/rust-embedded/cross.git#2f284acd)` (executable `cross`)

# cross build --target x86_64-pc-windows-gnu
Unable to find image 'rustembedded/cross:x86_64-pc-windows-gnu' locally
x86_64-pc-windows-gnu: Pulling from rustembedded/cross
<removed>
Digest: sha256:cdc542fe0a4b5cf89817388bcb4769f430a2979281add6f5e8fb26baf9f94a9a
Status: Downloaded newer image for rustembedded/cross:x86_64-pc-windows-gnu
sh: 1: cargo: not found
```

I tried to install cargo from master but running into the same issue. I'm using WSL. Any suggestions on how to troubleshoot further?

**Comment by urso** [comment]
Did run into a similar issue with development containers and Docker in Docker setup. I created a small POC (PR #387) that tries to find the corrects paths on the host machine when spinning up the child container.

**Comment by edenreich** [comment]
I can confirm this issue, it also happens on `armv7-unknown-linux-musleabihf-0.2.0`

shouldn't rust be installed in those container images ? or I misunderstood the way this tool works

```docker
FROM rustembedded/cross:armv7-unknown-linux-musleabihf-0.2.0

ENV PATH="$HOME/.cargo/bin:$PATH"

RUN curl https://sh.rustup.rs -sSf | \
    sh -s -- -y --default-toolchain stable

COPY src src
COPY Cargo.lock Cargo.lock
COPY Cargo.toml Cargo.toml
```

**Comment by balboah** [comment]
same problem, for some reason it worked a while ago. but not now (macOS)

**Comment by brainstorm** [comment]
I can confirm as well, started happening a couple of days ago. Here I'm not even using an official rustembedded docker image, but a relatively simple Alpine linux one (see https://github.com/rust-bio/rust-htslib/pull/193 if you need more details to reproduce and/or context):

```shell
$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/limsadmin/.rustup

installed targets for active toolchain
--------------------------------------

x86_64-unknown-linux-gnu
x86_64-unknown-linux-musl

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.42.0 (b8cedc004 2020-03-09)

$ cat Cross.toml
[target.x86_64-unknown-linux-musl]
image = "brainstorm/rust-htslib-musl-alpine:latest"
$ cat docker/Dockerfile.alpine
FROM alpine:edge

RUN apk add --update wget git g++ build-base automake autoconf openssl openssl-dev curl-dev bzip2-dev xz-dev zlib-dev rustup && \
    rm -rf /var/cache/apk/*

WORKDIR /root
RUN rustup-init -y

ENV PATH "/root/.cargo/bin:$PATH"
RUN rustup target add x86_64-unknown-linux-musl
$ cross build --target x86_64-unknown-linux-musl
sh: cargo: not found
```

**Comment by wucke13** [comment]
@reitermarkus Tagging you, as there seems to be official status on this, I hope you can provide more info.

Why is this issue still unfixed? @AluisioASG solution is a workaround that works, but it is rather inconvenient. How does `cross` pickup the host systems `cargo`? And why doesn't this mechanism work for some people (like me)? 

Would it be possible to have a `cargo` with the matching target already added in the containers as a fallback? So that if possible host `cargo` is used, if not container image's `cargo`?

**Comment by tylerarnold** [comment]
I am hitting this issue as well, running on MacOS 10.15 and docker-in-dockering it. If I change cross to the master branch, it fails out with "Could not find directory of OpenSSL installation," but openssl-dev is installed.

**Comment by kajalsinha** [comment]
I have the same problem running on rust:1.44-alpine
After running `apk add cmake make gcc libtool musl-dev g++`
I see `/bin/sh: 3: cargo: not found`

**Comment by efx** [comment]
I also ran into the problem on nixOS while trying to cross compile for `x86_64-unknown-linux-musl`.
I ended up using https://github.com/emk/rust-musl-builder#what-is-this since it worked out of the box for me.

**Comment by jjlin** [comment]
For those running `cross` from within a Docker image, see https://github.com/rust-embedded/cross/blob/master/README.md#docker-in-docker.

An example of doing this interactively using the official [`rust`](https://hub.docker.com/_/rust) image:
```
docker-host$ docker run -it -e CROSS_DOCKER_IN_DOCKER=true -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/usr/src/myproj -w /usr/src/myproj --rm rust bash
root@c7fddc07d311:/usr/src/myproj# wget https://download.docker.com/linux/static/stable/x86_64/docker-19.03.12.tgz
root@c7fddc07d311:/usr/src/myproj# tar -C /usr/local/bin --strip-components=1 -xf docker-19.03.12.tgz docker/docker
root@c7fddc07d311:/usr/src/myproj# cargo install cross
root@c7fddc07d311:/usr/src/myproj# cross build --target aarch64-unknown-linux-gnu
```

**Comment by jaredwolff** [comment]
While working on this pull request (#467), I started encountering this message. I had just recently changed the path configuration for `fish` where I was placing `/usr/local/bin` before the one for cargo at `~/.cargo/bin/`. Removing that entry seemed to clear up the issue. (As a side note, I'm on OSX running  10.14.6)

**Comment by andresv** [comment]
I am having trouble to get cross to work with circleci.
I have following `config.yml`:
```
version: 2.1

executors:
  ci-runner:
    docker:
      - image: cimg/rust:1.47.0

jobs:
  build:
    docker:
      - image: cimg/rust:1.47.0
    environment:
      CROSS_DOCKER_IN_DOCKER: true
    steps:
      - checkout
      - restore_cache:
          key: v1-cargo-cross
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Install protobuf dependencies
          command: |
            sudo apt-get update
            sudo apt install protobuf-compiler
      - run:
          name: Install cargo cross
          command: |
            set -x
            CROSS=/home/circleci/.cargo/bin/cross
            if [ -f "$CROSS" ]; then
              echo "cargo cross already installed"
            else
              cargo install cross
            fi
      - save_cache:
          key: v1-cargo-cross
          paths: /home/circleci/.cargo/bin/cross
      # - run:
      #     name: Build for x86_64
      #     command: cargo build
      - run:
          name: Build for aarch64
          command: docker run -e CROSS_DOCKER_IN_DOCKER=true -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/home/circleci/project -w /home/circleci/project rustembedded/cross:aarch64-unknown-linux-musl cross build --target aarch64-unknown-linux-musl

workflows:
  version: 2
  app:
    jobs:
      - build
```

And I get error that `cross` is not found:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"cross\": executable file not found in $PATH": unknown.
```

Maybe there is some obvious error in this docker command?
