### ISSUE TITLE
Cross.toml: runner setting is ignored

### ISSUE THREAD

**Issue by japaric** [rust-embedded/cross#499]
``` toml
# Cross.toml
[target.aarch64-unknown-linux-gnu]
runner = ["qemu-system"]
```

The above setting is ignored by `cross`.

As you can see in https://github.com/rust-embedded/cross/blob/8df1f8cd2fe6d09cf312fd4c2cd498499ebc423d/src/docker.rs#L106 and https://github.com/rust-embedded/cross/blob/8df1f8cd2fe6d09cf312fd4c2cd498499ebc423d/src/docker.rs#L176

The `CROSS_RUNNER` variable is always set to `""` in the docker container.

Apparently, the issue was (unintentionally) introduced in #344.
