### ISSUE TITLE
cargo alias doesn't work on cross

### ISSUE THREAD

**Issue by XyLyXyRR** [rust-embedded/cross#562]
## Environment

* **Rust toolchain version:** rustc 1.52.1 (9bc8c42bb 2021-05-09)
* **IDE name and version:** intellij-idea-community-edition 4:2021.1.1-1
* **Operating system:** arch linux

## Problem description

Cargo alias doesn't work on cross.

`~/.cargo/config.toml`

```toml
[alias]
dbr = "build --target aarch64-linux-android --release"
```

`cross dbr` complie failed, but `cross build --target aarch64-linux-android --release` worked.

## Steps to reproduce

* cargo new one && cd one
* add `rustls` to `Cargo.toml`
* execute `cross dbr`

```toml
rustls = "0.19"
```
